### ISSUE TITLE
npm package?

### ISSUE THREAD

**Issue by isocra** [jvitela/mustache-wax#1]
Hi,

I love your extension to mustache, it adds just what I need 😄. However I really need it as an npm package so that I can easily install it in my code.

To see how easy/hard this would be, I created this repo https://github.com/isocra/mustache-format based on your code. 

Would you be interested in wrapping up your code as an npm package? If so, feel free to grab anything useful from my repo and then I'll remove it.

If not, do you mind if I do so? I'd obviously credit this repo and your work. Unfortunately it can't be published as `npm install mustache-wax` because someone has beaten you to that name.

Best wishes
Denis

**Comment by jvitela** [comment]
Hi, 

After some troubleshooting I finally manage to publish the library as an npm package. I also updated the README with instructions:  https://www.npmjs.com/package/@jvitela/mustache-wax

Sorry for the delayed response.
Cheers,
Jonathan.

**Comment by isocra** [comment]
Fantastic! Thanks
Denis
